KKK_Zusterna/KKK_Zusterna/Models/KategorijaPovezav/Povezave.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KKK_Zusterna.Models
{
    public class Povezave
    {
        #region Properties

        [Required]
        [Display(Name = "ID_Povezava:")]
        public int ID_Povezava { get; set; }

        [Required]
        [Display(Name = "ID_KategorijaPovezav:")]
        public int ID_KategorijaPovezav { get; set; }

        [Required]
        [Display(Name = "Naziv:")]
        public string Naziv { get; set; }

        [Required]
        [Display(Name = "URL:")]
        public string URL { get; set; }

        [Required]
        [Display(Name = "Spremenil")]
        public string Spremenil { get; set; }

        [Required]
        [Display(Name = "SpremenilDatum")]
        public DateTime SpremenilDatum { get; set; }
        
        #endregion

        #region LifeCycle

        public Povezave() { }

        #endregion
    }
}

KKK_Zusterna/KKK_Zusterna/Models/Kontakt/Kontakt.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KKK_Zusterna.Models
{
    public class Kontakt
    {
        #region Properties

        public int ID_Kontakt { get; set; }
        public string Spremenil { get; set; }
        public DateTime SpremenilDatum { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string Fax { get; set; }
        public string GSM { get; set; }
        public string Naslov { get; set; }

        #endregion

        #region Constructor

        public Kontakt(){}

        #endregion
    }
}

KKK_Zusterna/KKK_Zusterna/Models/Kontakt/KontaktPPP.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SQLite;
using System.Linq;
using System.Web;

namespace KKK_Zusterna.Models
{
    public class KontaktPPP
    {
        #region ConnectionString

        private string ConnString = System.Configuration.ConfigurationManager.ConnectionStrings["KKKZusternaDB"].ConnectionString;

        #endregion

        #region Functionality

        public Kontakt VrniKontakt()
        {
            Kontakt kontakt = null;

            string query = "SELECT * FROM Kontakt";

            SQLiteConnection conn = new SQLiteConnection(ConnString);

            conn.Open();

            SQLiteCommand cmd = new SQLiteCommand(conn);
            cmd.CommandText = query;

            SQLiteDataReader reader = cmd.ExecuteReader();

            DataSet ds = new DataSet();
            DataTable dt = new DataTable();

            ds.Tables.Add(dt);
            ds.EnforceConstraints = false;
            dt.Load(reader);

            conn.Dispose();

            if (dt.Rows != null && dt.Rows.Count > 0)
            {
                kontakt = new Kontakt();

                //Mapping
                kontakt.ID_Kontakt = (int)dt.Rows[0]["ID_Kontakt"];
                kontakt.Spremenil = dt.Rows[0]["Spremenil"] != null ? (string)dt.Rows[0]["Spremenil"] : "";
                kontakt.SpremenilDatum = dt.Rows[0]["SpremenilDatum"] != null ? (DateTime)dt.Rows[0]["SpremenilDatum"] : System.DateTime.Now;
                kontakt.Email = dt.Rows[0]["Email"] != null ? (string)dt.Rows[0]["Email"] : "";
                kontakt.Telefon = dt.Rows[0]["Telefon"] != null ? (string)dt.Rows[0]["Telefon"] : "";
                kontakt.Fax = dt.Rows[0]["Fax"] != null ? (string)dt.Rows[0]["Fax"] : "";
                kontakt.GSM = dt.Rows[0]["GSM"] != null ? (string)dt.Rows[0]["GSM"] : "";
                kontakt.Naslov = dt.Rows[0]["Naslov"] != null ? (string)dt.Rows[0]["Naslov"] : "";
            }

            return kontakt;
        }

        public void InsertKontakt(Kontakt kontakt)
        {
            string query = @"INSERT INTO Kontakt 
                             VALUES ('" + kontakt.ID_Kontakt + "', '" 
                                        + kontakt.Spremenil + "', DATETIME('now'), '" 
                                        + kontakt.Email + "', '" 
                                        + kontakt.Telefon + "', '" 
                                        + kontakt.Fax + "', '" 
                                        + kontakt.GSM + "', '"
                                        + kontakt.Naslov + "' )";

            SQLiteConnection conn = new SQLiteConnection(ConnString);

            conn.Open();

            SQLiteCommand cmd = new SQLiteCommand(conn);
            cmd.CommandText = query;

            cmd.ExecuteNonQuery();

            conn.Dispose();
        }

        public void UpdateKontakt(Kontakt kontakt)
        {
            string query = @"UPDATE Kontakt
                             SET Spremenil = '" + kontakt.Spremenil + "', " 
                                                + "SpremenilDatum = DATETIME('now'), "
                                                + "Email = '" + kontakt.Email + "', "
                                                + "Telefon = '" + kontakt.Telefon + "', "
                                                + "Fax = '" + kontakt.Fax + "', "
                                                + "GSM = '" + kontakt.GSM + "', "
                                                + "Naslov = '" + kontakt.Naslov + "' " +
                           "WHERE ID_Kontakt = '" + kontakt.ID_Kontakt + "'";

            SQLiteConnection conn = new SQLiteConnection(ConnString);

            conn.Open();

            SQLiteCommand cmd = new SQLiteCommand(conn);
            cmd.CommandText = query;

            cmd.ExecuteNonQuery();

            conn.Dispose();
        }

        public void DeleteKontakt()
        {
            string query = "DELETE FROM Kontakt";

            SQLiteConnection conn = new SQLiteConnection(ConnString);

            conn.Open();

            SQLiteCommand cmd = new SQLiteCommand(conn);
            cmd.CommandText = query;

            cmd.ExecuteNonQuery();

            conn.Dispose();
        }

        #endregion
    }
}

KKK_Zusterna/KKK_Zusterna/Models/ONas/ONas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KKK_Zusterna.Models
{
    public class ONas
    {
        #region Properties

        [Required]
        [Display(Name = "ID_ONas:")]
        public int ID_ONas { get; set; }

        [AllowHtml]
        [Display(Name = "Vsebina:")]
        public string Vsebina { get; set; }

        [Required]
        [Display(Name = "Spremenil")]
        public string Spremenil { get; set; }

        [Required]
        [Display(Name = "SpremenilDatum")]
        public DateTime SpremenilDatum { get; set; }
        
        #endregion

        #region LifeCycle

        public ONas(){}

        #endregion
    }
}

KKK_Zusterna/KKK_Zusterna/Models/ONas/ONasPPP.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SQLite;
using System.Linq;
using System.Web;

namespace KKK_Zusterna.Models
{
    public class ONasPPP
    {
        #region ConnectionString

        private string ConnString = System.Configuration.ConfigurationManager.ConnectionStrings["KKKZusternaDB"].ConnectionString;

        #endregion

        #region Functionality

        public ONas VrniONas()
        {
            ONas oNas = null;

            string query = @"SELECT ID_ONas, Vsebina, Spremenil, SpremenilDatum FROM ONas WHERE ID_ONas = 1";

            SQLiteConnection conn = new SQLiteConnection(ConnString);

            conn.Open();

            SQLiteCommand cmd = new SQLiteCommand(conn);
            cmd.CommandText = query;

            SQLiteDataReader reader = cmd.ExecuteReader();

            DataSet ds = new DataSet();
            DataTable dt = new DataTable();

            ds.Tables.Add(dt);
            ds.EnforceConstraints = false;
            dt.Load(reader);

            conn.Dispose();

            if (dt != null && dt.Rows.Count > 0)
            {
                oNas = new ONas();

                oNas.ID_ONas = (int)dt.Rows[0]["ID_ONas"];
                oNas.Vsebina = dt.Rows[0]["Vsebina"] != null ? (string)dt.Rows[0]["Vsebina"] : "";
                oNas.Spremenil = dt.Rows[0]["Spremenil"] != null ? (string)dt.Rows[0]["Spremenil"] : "";
                oNas.SpremenilDatum = dt.Rows[0]["SpremenilDatum"] != null ? (DateTime)dt.Rows[0]["SpremenilDatum"] : System.DateTime.Now;
            }

            return oNas;
        }

        public void ShraniONas(ONas tmpONas)
        {
            string query = @"INSERT INTO ONas 
                             VALUES ('" + tmpONas.ID_ONas + "', '" + tmpONas.Vsebina + "', '" + tmpONas.Spremenil + "', DATETIME('now'))";

            SQLiteConnection conn = new SQLiteConnection(ConnString);

            conn.Open();

            SQLiteCommand cmd = new SQLiteCommand(conn);
            cmd.CommandText = query;

            cmd.ExecuteNonQuery();

            conn.Dispose();
        }

        public void ZbrisiONas()
        {
            string query = @"DELETE FROM ONas";

            SQLiteConnection conn = new SQLiteConnection(ConnString);

            conn.Open();

            SQLiteCommand cmd = new SQLiteCommand(conn);
            cmd.CommandText = query;

            cmd.ExecuteNonQuery();

            conn.Dispose();
        }

        public void UrediONas(ONas oNas)
        {
            string query = @"UPDATE ONas 
                             SET Vsebina = '" + oNas.Vsebina + "', Spremenil = '" + oNas.Spremenil + "', SpremenilDatum = DATETIME('now')";

            SQLiteConnection conn = new SQLiteConnection(ConnString);

            conn.Open();

            SQLiteCommand cmd = new SQLiteCommand(conn);
            cmd.CommandText = query;

            cmd.ExecuteNonQuery();

            conn.Dispose();
        }

        #endregion
    }
}

KKK_Zusterna/KKK_Zusterna/Controllers/KlubskiKoticekController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using KKK_Zusterna.Helper;
using KKK_Zusterna.Models;
using log4net;

namespace KKK_Zusterna.Controllers
{
    public class KlubskiKoticekController : Controller
    {
        #region Properties

        ILog logger = LogManager.GetLogger(typeof(KlubskiKoticekController));

        ONasPPP UpraviteljONas = new ONasPPP();

        KontaktPPP UpraviteljKontakt = new KontaktPPP();

        KategorijaPovezavPPP UpraviteljKategorijPovezav = new KategorijaPovezavPPP();
        PovezavePPP UpraviteljPovezav = new PovezavePPP();

        #endregion

        #region ONas

        public ActionResult ONas()
        {
            ONas oNas = null;

            try
            {
                //Zbrisemo obvestila && napake
                GlobalNotifications.ZbrisiObvestilo();
                GlobalErrors.ZbrisiNapake();
                GlobalWarnings.ZbrisiOpozorilo();

                oNas = UpraviteljONas.VrniONas();

                //Obvestilo o uspehu akcije if TrenutniUporabnik != null
                if (System.Web.HttpContext.Current.User.Identity.IsAuthenticated)
                {
                    GlobalNotifications.DodajObvestilo(GlobalNotifications.UspehOperacije);
                }
            }
            catch (Exception ex)
            {
                GlobalErrors.ZbrisiNapake();
                GlobalErrors.DodajNapako(ex.ToString());
                MailHelper.SendMailForErrors("ONas", ex.ToString());
                logger.Error("ERROR in method " + MethodInfo.GetCurrentMethod() + ": " + ex);
            }

            return View(oNas);
        }

        #endregion

        #region Kontakt

        #region Kontakt

        public ActionResult Kontakt()
        {
            Kontakt kontakt = null;

            try
            {
                //Zbrisemo obvestila && napake
                GlobalNotifications.ZbrisiObvestilo();
                GlobalErrors.ZbrisiNapake();
                GlobalWarnings.ZbrisiOpozorilo();

                kontakt = UpraviteljKontakt.VrniKontakt();

                //Obvestilo o uspehu akcije if TrenutniUporabnik != null
                if (System.Web.HttpContext.Current.User.Identity.IsAuthenticated)
                {
                    GlobalNotifications.DodajObvestilo(GlobalNotifications.UspehOperacije);
                }
            }
            catch (Exception ex)
            {
                GlobalErrors.ZbrisiNapake();
                GlobalErrors.DodajNapako(ex.ToString());
                MailHelper.SendMailForErrors("Kontakt", ex.ToString());
                logger.Error("ERROR in method " + MethodInfo.GetCurrentMethod() + ": " + ex);
            }

            return View(kontakt);
        }

        #endregion

        #region PosljiMail

        [HttpPost, ValidateInput(false)]
        public ActionResult PosljiMail(string Ime, string Priimek, string Email, string Vsebina)
        {
            try
            {
                //Zbrisemo obvestila && napake
                GlobalNotifications.ZbrisiObvestilo();
                GlobalErrors.ZbrisiNapake();
                GlobalWarnings.ZbrisiOpozorilo();

                //Send email
                MailHelper.SendMailFromKontaktForm(Ime, Priimek, Email, Vsebina);

                //Obvestilo o uspehu akcije
                GlobalNotifications.DodajObvestilo(GlobalNotifications.UspehOperacije);
            }
            catch (Exception ex)
            {
                GlobalErrors.ZbrisiNapake();
                GlobalErrors.DodajNapako(ex.ToString());
                MailHelper.SendMailForErrors("PosljiMail", ex.ToString());
                logger.Error("ERROR in method " + MethodInfo.GetCurrentMethod() + ": " + ex);
            }

            return View("Kontakt");
        }

        #endregion

        #endregion

        #region Povezave

        public ActionResult Povezave()
        {
            List<PovezavePlus> seznamForView = null;

            try
            {
                //Zbrisemo obvestila && napake
                GlobalNotifications.ZbrisiObvestilo();
                GlobalErrors.ZbrisiNapake();
                GlobalWarnings.ZbrisiOpozorilo();

                #region Get data

                seznamForView = new List<PovezavePlus>();

                List<KategorijaPovezavGrid> seznamKategorijPovezav = UpraviteljKategorijPovezav.VrniKategorijePovezav();
                foreach (KategorijaPovezavGrid kategorijaPovezav in seznamKategorijPovezav)
                {
                    PovezavePlus povezavePlus = new PovezavePlus();
                    povezavePlus.ID_KategorijaPovezav = kategorijaPovezav.ID_KategorijaPovezav;
                    povezavePlus.Naslov = kategorijaPovezav.Naslov;
                    povezavePlus.Spremenil = kategorijaPovezav.Spremenil;
                    povezavePlus.SpremenilDatum = kategorijaPovezav.SpremenilDatum;

                    List<PovezaveGrid> seznamPovezav = UpraviteljPovezav.VrniPovezaveZaKategorijo(kategorijaPovezav.ID_KategorijaPovezav);
                    povezavePlus.SeznamPovezav = seznamPovezav;

                    seznamForView.Add(povezavePlus);
                }

                if (seznamForView.Count < 1)
                {
                    seznamForView = null;
                }

                #endregion

                //Obvestilo o uspehu akcije if TrenutniUporabnik != null
                if (System.Web.HttpContext.Current.User.Identity.IsAuthenticated)
                {
                    GlobalNotifications.DodajObvestilo(GlobalNotifications.UspehOperacije);
                }

            }
            catch (Exception ex)
            {
                GlobalErrors.ZbrisiNapake();
                GlobalErrors.DodajNapako(ex.ToString());
                MailHelper.SendMailForErrors("Povezave", ex.ToString());
                logger.Error("ERROR in method " + MethodInfo.GetCurrentMethod() + ": " + ex);
            }

            return View(seznamForView);
        }

        #endregion
    }
}

KKK_Zusterna/KKK_Zusterna/Views/KlubskiKoticek/Kontakt.cshtml
@model KKK_Zusterna.Models.Kontakt

@{
    ViewBag.Title = "Kajak kanu klub Žusterna";
}

<div class="span12">
    
    @if (KKK_Zusterna.Models.GlobalErrors.seznamNapak != null && KKK_Zusterna.Models.GlobalErrors.seznamNapak.Count > 0)
    {
        foreach (string napaka in KKK_Zusterna.Models.GlobalErrors.seznamNapak)
        {
            <div class="row-fluid">
                <div class="span12">
                    <div class="alert alert-error">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>Napaka!</strong><br /> @napaka
                    </div> 
                </div>
            </div> 
        }
    }
    
    @if (KKK_Zusterna.Models.GlobalWarnings.seznamOpozoril != null && KKK_Zusterna.Models.GlobalWarnings.seznamOpozoril.Count > 0)
    {
        foreach (string opozorilo in KKK_Zusterna.Models.GlobalWarnings.seznamOpozoril)
        {
            <div class="row-fluid">
                <div class="span12">
                    <div class="alert alert-info">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>Opozorilo!</strong><br /> @opozorilo
                    </div> 
                </div>
            </div> 
        }
    }

    @if (KKK_Zusterna.Models.GlobalNotifications.seznamObvestil != null && KKK_Zusterna.Models.GlobalNotifications.seznamObvestil.Count > 0)
    {
        foreach (string obvestilo in KKK_Zusterna.Models.GlobalNotifications.seznamObvestil)
        {
            <div class="row-fluid">
                <div class="span12">
                    <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>Opravljeno! </strong>@obvestilo 
                    </div>
                </div>
            </div>
        }
    }
    
    <ul class="breadcrumb alert alert-info">
        <li class="active">Kontakt</li>
    </ul> 
    
    @if (Model != null)
    {
        <div class="row-fluid">
            <div class="span12">
                <form class="form-inline">
                    <label class="control-label"><b>E-mail:</b></label>
                    <label class="control-label"><a href="mailto: @Model.Email">@Model.Email</a></label>
                </form>
            </div>
        </div>
    
        <div class="row-fluid">
            <div class="span12">
                <form class="form-inline">
                    <label class="control-label"><b>Tel.:</b></label>
                    <label class="control-label">@Model.Telefon</label>
                </form>
            </div>
        </div>
        
        <div class="row-fluid">
            <div class="span12">
                <form class="form-inline">
                    <label class="control-label"><b>Fax:</b></label>
                    <label class="control-label">@Model.Fax</label>
                </form>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span12">
                <form class="form-inline">
                    <label class="control-label"><b>Gsm:</b></label>
                    <label class="control-label">@Model.GSM</label>
                </form>
            </div>
        </div>
    
        <div class="row-fluid">
            <div class="span12">
                <form class="form-inline">
                    <label class="control-label"><b>Naslov:</b></label>
                    <label class="control-label">@Model.Naslov</label>
                </form>
            </div>
        </div>
    }
    
    <div class="row-fluid">
        <div class="span12">
            <legend>Pišite nam:</legend>    
        </div>
    </div>
     
    @using (Html.BeginForm("PosljiMail", "KlubskiKoticek", FormMethod.Post))
    {
        <div class="row-fluid">
            <div class="row-fluid">
                <div class="span12">
                    <label>Vpišite vaše ime:</label>
                    <input name="Ime" type="text" width="100%" placeholder="Ime ..." class="input-block-level" required/>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span12">
                    <label>Vpišite vaš priimek:</label>
                    <input name="Priimek" type="text" width="100%" placeholder="Priimek ..." class="input-block-level" required/>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span12">
                    <label>Vpišite vaš e-naslov:</label>
                    <input name="Email" type="email" width="100%" placeholder="Email ..." class="input-block-level" required/>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span12">
                    <label>Vpišite vsebino:</label>
                    <textarea name="Vsebina" type="text" id="KontaktVsebina" width="100%" placeholder="Vsebina ..." class="input-block-level" rows="15" required></textarea>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span12">
                    <div class="control-group">
                        <div class="controls">
                            <button class="btn btn-primary" type="submit"><i class="icon-envelope icon-white"></i>  Pošlji</button>  
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
      
</div>

KKK_Zusterna/KKK_Zusterna/Views/KlubskiKoticek/ONas.cshtml
@model KKK_Zusterna.Models.ONas

@{
    ViewBag.Title = "Kajak kanu klub Žusterna";
}

<div class="span12">
    
    @if (KKK_Zusterna.Models.GlobalErrors.seznamNapak != null && KKK_Zusterna.Models.GlobalErrors.seznamNapak.Count > 0)
    {
        foreach (string napaka in KKK_Zusterna.Models.GlobalErrors.seznamNapak)
        {
            <div class="row-fluid">
                <div class="span12">
                    <div class="alert alert-error">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>Napaka!</strong><br /> @napaka
                    </div> 
                </div>
            </div> 
        }
    }
    
    @if (KKK_Zusterna.Models.GlobalWarnings.seznamOpozoril != null && KKK_Zusterna.Models.GlobalWarnings.seznamOpozoril.Count > 0)
    {
        foreach (string opozorilo in KKK_Zusterna.Models.GlobalWarnings.seznamOpozoril)
        {
            <div class="row-fluid">
                <div class="span12">
                    <div class="alert alert-info">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>Opozorilo!</strong><br /> @opozorilo
                    </div> 
                </div>
            </div> 
        }
    }
    
    @if (KKK_Zusterna.Models.GlobalNotifications.seznamObvestil != null && KKK_Zusterna.Models.GlobalNotifications.seznamObvestil.Count > 0)
    {
        foreach (string obvestilo in KKK_Zusterna.Models.GlobalNotifications.seznamObvestil)
        {
            <div class="row-fluid">
                <div class="span12">
                    <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>Opravljeno! </strong>@obvestilo 
                    </div>
                </div>
            </div>
        }
    }  
    
    @if (Model != null)
    {
        <ul class="breadcrumb alert alert-info">
          <li class="active">O nas</li>
        </ul>
        
        <div class="row-fluid">
            <div class="span12">
                <p>@(new HtmlString(Model.Vsebina))</p>
            </div>
        </div>
        
        <div class="row-fluid">
            <div class="span12">
                <legend>Informacije:</legend>    
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <span class="muted">Objavil: @Model.Spremenil</span>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <span class="muted">Datum objave: @Model.SpremenilDatum</span>
            </div>
        </div>
    }
    else
    {
        <div class="row-fluid">
            <div class="span12">
                <div class="alert alert-info">
                    <button type="button" class="close" data-dismiss="alert">
                        &times;</button>
                    <strong>Opozorilo!</strong> Ni dodane vsebine.
                </div>
            </div>
        </div>
        
        <ul class="breadcrumb alert alert-info">
          <li class="active">O nas</li>
        </ul>
    }

</div>

KKK_Zusterna/KKK_Zusterna/Views/KlubskiKoticek/Povezave.cshtml
@model List<KKK_Zusterna.Models.PovezavePlus>

@{
    ViewBag.Title = "Kajak kanu klub Žusterna";
}

<div class="span12">
    
    @if (KKK_Zusterna.Models.GlobalErrors.seznamNapak != null && KKK_Zusterna.Models.GlobalErrors.seznamNapak.Count > 0)
    {
        foreach (string napaka in KKK_Zusterna.Models.GlobalErrors.seznamNapak)
        {
            <div class="row-fluid">
                <div class="span12">
                    <div class="alert alert-error">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>Napaka!</strong><br /> @napaka
                    </div> 
                </div>
            </div> 
        }
    }
    
    @if (KKK_Zusterna.Models.GlobalWarnings.seznamOpozoril != null && KKK_Zusterna.Models.GlobalWarnings.seznamOpozoril.Count > 0)
    {
        foreach (string opozorilo in KKK_Zusterna.Models.GlobalWarnings.seznamOpozoril)
        {
            <div class="row-fluid">
                <div class="span12">
                    <div class="alert alert-info">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>Opozorilo!</strong><br /> @opozorilo
                    </div> 
                </div>
            </div> 
        }
    }
    
    @if (KKK_Zusterna.Models.GlobalNotifications.seznamObvestil != null && KKK_Zusterna.Models.GlobalNotifications.seznamObvestil.Count > 0)
    {
        foreach (string obvestilo in KKK_Zusterna.Models.GlobalNotifications.seznamObvestil)
        {
            <div class="row-fluid">
                <div class="span12">
                    <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>Opravljeno! </strong>@obvestilo 
                    </div>
                </div>
            </div>
        }
    }  
      
    @if (Model != null && Model.Count > 0)
    {
        <ul class="breadcrumb alert alert-info">
          <li class="active">Povezave</li>
        </ul>

        foreach (var povezava in Model)
        {
            <div class="row-fluid">
                <div class="span12">
                    <div class="row-fluid">
                        <div class="span12">
                            <h4>@povezava.Naslov</h4>
                        </div>
                    </div>
                    @for (int j = 0; j < povezava.SeznamPovezav.Count; j++)
                    {
                        <div class="row-fluid">
                            <div class="span12">
                                <a target="_blank" href="@povezava.SeznamPovezav[j].URL"><i class="icon-chevron-right" style="margin-top: 1px"></i> @povezava.SeznamPovezav[j].Naziv</a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        
            <div class="row-fluid">
                <div class="span12">
                </div>
            </div>
        }
    }
    else
    {
        <div class="row-fluid">
            <div class="span12">
                <div class="alert alert-info">
                    <button type="button" class="close" data-dismiss="alert">
                        &times;</button>
                    <strong>Opozorilo!</strong> Ni dodanih povezav.
                </div>
            </div>
        </div>
        
        <ul class="breadcrumb alert alert-info">
          <li class="active">Povezave</li>
        </ul>
    }

</div>