KKK_Zusterna/KKK_Zusterna/Models/GalerijaSlik/GalerijaKategorija.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KKK_Zusterna.Models
{
    public class GalerijaKategorija
    {
        #region Properties

        [Required]
        [Display(Name = "Kategorija:")]
        public int ID_galerijaKategorija { get; set; }

        [Required]
        [Display(Name = "Naslov:")]
        public string Naslov { get; set; }

        [Required]
        [Display(Name = "URL Slika:")]
        public string URLSlika { get; set; }

        [Display(Name = "Spremenil uporabnik:")]
        public string SpremenilUporabnik { get; set; }

        [Display(Name = "URL Slika:")]
        public DateTime SpremenilDatum { get; set; }

        #endregion

        #region LifeCycle

        public GalerijaKategorija(){}

        #endregion
    }
}

KKK_Zusterna/KKK_Zusterna/Models/KategorijaPovezav/KategorijaPovezav.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KKK_Zusterna.Models
{
    public class KategorijaPovezav
    {
        #region Properties

        [Required]
        [Display(Name = "ID_KategorijaPovezav:")]
        public int ID_KategorijaPovezav { get; set; }

        [Required]
        [Display(Name = "Naslov:")]
        public string Naslov { get; set; }

        [Required]
        [Display(Name = "Spremenil")]
        public string Spremenil { get; set; }

        [Required]
        [Display(Name = "SpremenilDatum")]
        public DateTime SpremenilDatum { get; set; }
        
        #endregion

        #region LifeCycle

        public KategorijaPovezav() { }

        #endregion
    }
}

KKK_Zusterna/KKK_Zusterna/Models/KategorijaPovezav/KategorijaPovezavGrid.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KKK_Zusterna.Models
{
    public class KategorijaPovezavGrid
    {
        #region Properties

        public int ID_KategorijaPovezav { get; set; }
        public string Naslov { get; set; }
        public string Spremenil { get; set; }
        public DateTime SpremenilDatum { get; set; }

        #endregion
    }
}

KKK_Zusterna/KKK_Zusterna/Models/KategorijaPovezav/Povezave.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KKK_Zusterna.Models
{
    public class Povezave
    {
        #region Properties

        [Required]
        [Display(Name = "ID_Povezava:")]
        public int ID_Povezava { get; set; }

        [Required]
        [Display(Name = "ID_KategorijaPovezav:")]
        public int ID_KategorijaPovezav { get; set; }

        [Required]
        [Display(Name = "Naziv:")]
        public string Naziv { get; set; }

        [Required]
        [Display(Name = "URL:")]
        public string URL { get; set; }

        [Required]
        [Display(Name = "Spremenil")]
        public string Spremenil { get; set; }

        [Required]
        [Display(Name = "SpremenilDatum")]
        public DateTime SpremenilDatum { get; set; }
        
        #endregion

        #region LifeCycle

        public Povezave() { }

        #endregion
    }
}

KKK_Zusterna/KKK_Zusterna/Models/KategorijaPovezav/PovezaveGrid.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KKK_Zusterna.Models
{
    public class PovezaveGrid
    {
        #region Properties

        public int ID_Povezava { get; set; }
        public int ID_KategorijaPovezav { get; set; }
        public string Naziv { get; set; }
        public string URL { get; set; }
        public string Spremenil { get; set; }
        public DateTime SpremenilDatum { get; set; }

        #endregion
    }
}

KKK_Zusterna/KKK_Zusterna/Models/KategorijaPovezav/PovezavePlus.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KKK_Zusterna.Models
{
    public class PovezavePlus
    {
        #region Properties

        public int ID_KategorijaPovezav { get; set; }
        public string Naslov { get; set; }
        public string Spremenil { get; set; }
        public DateTime SpremenilDatum { get; set; }
        public List<PovezaveGrid> SeznamPovezav { get; set; }

        #endregion

        #region Constructor

        public PovezavePlus(){}

        #endregion
    }
}

KKK_Zusterna/KKK_Zusterna/Models/Rezultati/LetoRezultati.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace KKK_Zusterna.Models
{
    public class LetoRezultati
    {
        #region Properties

        [Required]
        [Display(Name = "Id:")]
        public int ID_letoRezultati { get; set; }

        [Required]
        [Display(Name = "Leto:")]
        public string Leto { get; set; }

        [Required]
        [Display(Name = "Spremenil:")]
        public string Spremenil { get; set; }

        [Required]
        [Display(Name = "Datum spremembe:")]
        public DateTime SpremenilDatum { get; set; }

        #endregion

        #region LifeCycle

        public LetoRezultati(){}

        #endregion
    }
}

KKK_Zusterna/KKK_Zusterna/Models/Tekmovanja/LetoTekmovanja.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KKK_Zusterna.Models
{
    public class LetoTekmovanja
    {
        #region Properties

        [Required]
        [Display(Name = "Id:")]
        public int ID_letoTekmovanja { get; set; }

        [Required]
        [Display(Name = "Leto:")]
        public string Leto { get; set; }

        [Required]
        [Display(Name = "Spremenil:")]
        public string Spremenil { get; set; }

        [Required]
        [Display(Name = "Datum spremembe:")]
        public DateTime SpremenilDatum { get; set; }

        #endregion

        #region LifeCycle

        public LetoTekmovanja() { }

        #endregion
    }
}

KKK_Zusterna/KKK_Zusterna/Controllers/AdministracijaController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using KKK_Zusterna.Helper;
using KKK_Zusterna.Models;
using System.Drawing;
using KKK_Zusterna.Enums;
using PagedList;
using log4net;
using System.Reflection;

namespace KKK_Zusterna.Controllers
{
    public class AdministracijaController : Controller
    {
        #region Properties

        ILog logger = LogManager.GetLogger(typeof(AdministracijaController));

        public UporabnikPPP UpraviteljUporabnik = new UporabnikPPP();

        public NovicaPPP UpraviteljNovica = new NovicaPPP();
        public NovicaPrilogaPPP UpraviteljNovicaPriloga = new NovicaPrilogaPPP();

        public ONasPPP UpraviteljONas = new ONasPPP();

        public KontaktPPP UpraviteljKontakt = new KontaktPPP();

        public KategorijaPovezavPPP UpraviteljKategorijePovezav = new KategorijaPovezavPPP();
        public PovezavePPP UpraviteljPovezav = new PovezavePPP();

        public TreningPPP UpraviteljTrening = new TreningPPP();

        public LetoTekmovanjaPPP UpraviteljLetoTekmovanja = new LetoTekmovanjaPPP();
        public TekmovanjaPPP UpraviteljTekmovanja = new TekmovanjaPPP();

        public LetoRezultatiPPP UpraviteljLetoRezultati = new LetoRezultatiPPP();
        public RezultatiPPP UpraviteljRezultati = new RezultatiPPP();

        public GalerijaKategorijaPPP UpraviteljGalerijaKategorija = new GalerijaKategorijaPPP();
        public GalerijaPPP UpraviteljGalerija = new GalerijaPPP();

        #endregion

        #region Uporabniki

        #region Prijava

        [HttpPost]
        public ActionResult Prijava(string email, string geslo)
        {
            int pageSize = 4;
            int pageNumber = 1;

            List<NovicaGrid> novice = null;

            try
            {
                //Zbrisemo obvestila && napake
                GlobalNotifications.ZbrisiObvestilo();
                GlobalErrors.ZbrisiNapake();
                GlobalWarnings.ZbrisiOpozorilo();

                //Get novice
                novice = UpraviteljNovica.VrniNovice();

                //Get uporabnik
                Uporabnik m_trenutniUporabnik = UpraviteljUporabnik.VrniUporabnika(email, geslo);

                if (m_trenutniUporabnik != null)
                {
                    FormsAuthentication.SetAuthCookie(m_trenutniUporabnik.Email, true);
                    
                    //Move to new thread for better performance
                    logger.Info("User " + m_trenutniUporabnik.Email + " has logged in.");
                    Thread thread = new Thread(() => MailHelper.SendMailForUserLogin(m_trenutniUporabnik.Email));
                    thread.Start();

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    GlobalErrors.DodajNapako(GlobalErrors.napakaPrijava);
                    logger.Info("User " + email + " is not a valid user!");

                    return View("../Home/Index", novice.ToPagedList(pageNumber, pageSize));
                }
            }
            catch (Exception ex)
            {
                GlobalErrors.ZbrisiNapake();
                GlobalErrors.DodajNapako(ex.ToString());
                MailHelper.SendMailForErrors("Prijava", ex.ToString());
                logger.Error("ERROR in method " + MethodInfo.GetCurrentMethod() + ": " + ex);

                return View("../Home/Index", novice.ToPagedList(pageNumber, pageSize));
            }
        }

        #endregion

        #region VrniRegistracijaForma

        public ActionResult VrniRegistracijaForma()
        {
            try
            {
                //Zbrisemo obvestila && napake
                GlobalNotifications.ZbrisiObvestilo();
                GlobalErrors.ZbrisiNapake();
                GlobalWarnings.ZbrisiOpozorilo();
                
                //Obvestilo o uspehu akcije if TrenutniUporabnik != null
                if (System.Web.HttpContext.Current.User.Identity.IsAuthenticated)
                {
                    GlobalNotifications.DodajObvestilo(GlobalNotifications.UspehOperacije);
                }
            }
            catch (Exception ex)
            {
                GlobalErrors.ZbrisiNapake();
                GlobalErrors.DodajNapako(ex.ToString());
                logger.Error("ERROR in method " + MethodInfo.GetCurrentMethod() + ": " + ex);
            }

            return View();
        }

        #endregion

        #region RegistrirajUporabnika

        [HttpPost, ValidateInput(false)]
        public ActionResult RegistrirajUporabnika(string Email, string Ime, string Priimek, string Geslo, string PonoviGeslo)
        {
            try
            {
                //Zbrisemo obvestila && napake
                GlobalNotifications.ZbrisiObvestilo();
                GlobalErrors.ZbrisiNapake();
                GlobalWarnings.ZbrisiOpozorilo();

                if (Geslo.Equals(PonoviGeslo))
                {
                    #region Mapping

                    Uporabnik novi = new Uporabnik();

                    novi.Email = Email;
                    novi.Ime = Ime;
                    novi.Priimek = Priimek;
                    novi.Geslo = Geslo;

                    #endregion

                    MailHelper.SendMailForUserRegistration(novi);

                    //Obvestilo o uspehu akcije
                    GlobalNotifications.DodajObvestilo("Podatki so bili uspešno poslani administratorju strani. V kolikor bo zahtevek odobren boste na vaš email prejeli uporabniško ime in geslo."); 
                }
                else
                {
                    GlobalErrors.DodajNapako("Gesli se ne ujemata.");
                }
            }
            catch (Exception ex)
            {
                GlobalErrors.ZbrisiNapake();
                GlobalErrors.DodajNapako(ex.ToString());
                logger.Error("ERROR in method " + MethodInfo.GetCurrentMethod() + ": " + ex);
            }

            return View("VrniRegistracijaForma");
        }

        #endregion

        #region VrniUrediProfilForma

        [Authorize]
        public ActionResult VrniUrediProfilForma(string Email)
        {
            try
            {
                //Zbrisemo obvestila && napake
                GlobalNotifications.ZbrisiObvestilo();
                GlobalErrors.ZbrisiNapake();
                GlobalWarnings.ZbrisiOpozorilo();

                Uporabnik tmp = UpraviteljUporabnik.VrniUporabnika(Email);

                ViewBag.Data = tmp;

                //Obvestilo o uspehu akcije
                GlobalNotifications.DodajObvestilo(GlobalNotifications.UspehOperacije);
            }
            catch (Exception ex)
            {
                GlobalErrors.ZbrisiNapake();
                GlobalErrors.DodajNapako(ex.ToString());
                MailHelper.SendMailForErrors("VrniUrediProfilForma", ex.ToString());
                logger.Error("ERROR in method " + MethodInfo.GetCurrentMethod() + ": " + ex);
            }

            return View();
        }

        #endregion

        #region VrniSpremeniGesloForma

        [Authorize]
        public ActionResult VrniSpremeniGesloForma(string Email)
        {
            try
            {
                //Zbrisemo obvestila && napake
                GlobalNotifications.ZbrisiObvestilo();
                GlobalErrors.ZbrisiNapake();
                GlobalWarnings.ZbrisiOpozorilo();

                Uporabnik tmpUporabnik = UpraviteljUporabnik.VrniUporabnika(Email);
                ViewBag.Data = tmpUporabnik;

                //Obvestilo o uspehu akcije
                GlobalNotifications.DodajObvestilo(GlobalNotifications.UspehOperacije);
            }
            catch (Exception ex)
            {
                GlobalErrors.ZbrisiNapake();
                GlobalErrors.DodajNapako(ex.ToString());
                MailHelper.SendMailForErrors("VrniSpremeniGesloForma", ex.ToString());
                logger.Error("ERROR in method " + MethodInfo.GetCurrentMethod() + ": " + ex);
            }

            return View();
        }

        #endregion

        #region UpdateGesloUporabnik

        [HttpPost]
        [Authorize]
        public ActionResult UpdateGesloUporabnik(int ID_uporabnik, string TrenutnoGeslo, string NovoGeslo, string PonoviNovoGeslo)
        {
            try
            {
                //Zbrisemo obvestila && napake
                GlobalNotifications.ZbrisiObvestilo();
                GlobalErrors.ZbrisiNapake();
                GlobalWarnings.ZbrisiOpozorilo();

                bool uspesnaValidacija = true;

                #region Validacija

                if (String.IsNullOrEmpty(TrenutnoGeslo))
                {
                    GlobalWarnings.DodajOpozorilo(GlobalWarnings.TrenutnoGesloPrazno);
                    uspesnaValidacija = false;
                }

                if (string.IsNullOrEmpty(NovoGeslo) || string.IsNullOrEmpty(PonoviNovoGeslo))
                {
                    GlobalWarnings.DodajOpozorilo(GlobalWarnings.NovoGesloPrazno);
                    uspesnaValidacija = false;
                }

                #endregion

                if (uspesnaValidacija)
                {
                    if (NovoGeslo.Equals(PonoviNovoGeslo))
                    {
                        Uporabnik tmpUporabnik = UpraviteljUporabnik.VrniUporabnika(ID_uporabnik);

                        #region MD5 hash

                        MD5 md5 = new MD5CryptoServiceProvider();
                        md5.ComputeHash(ASCIIEncoding.ASCII.GetBytes(TrenutnoGeslo));
                        byte[] enterPasswordBytes = md5.Hash;
                        string enterPassword = Convert.ToBase64String(enterPasswordBytes);

                        #endregion

KKK_Zusterna/KKK_Zusterna/Views/Administracija/GalerijaKategorijaPodrobnosti.cshtml
@{
    ViewBag.Title = "Kajak kanu klub Žusterna";
}

<div class="span12">
    
    @if (KKK_Zusterna.Models.GlobalErrors.seznamNapak != null && KKK_Zusterna.Models.GlobalErrors.seznamNapak.Count > 0)
    {
        foreach (string napaka in KKK_Zusterna.Models.GlobalErrors.seznamNapak)
        {
            <div class="row-fluid">
                <div class="span12">
                    <div class="alert alert-error">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>Napaka!</strong><br /> @napaka
                    </div> 
                </div>
            </div> 
        }
    }
    
    @if (KKK_Zusterna.Models.GlobalWarnings.seznamOpozoril != null && KKK_Zusterna.Models.GlobalWarnings.seznamOpozoril.Count > 0)
    {
        foreach (string opozorilo in KKK_Zusterna.Models.GlobalWarnings.seznamOpozoril)
        {
            <div class="row-fluid">
                <div class="span12">
                    <div class="alert alert-info">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>Opozorilo!</strong><br /> @opozorilo
                    </div> 
                </div>
            </div> 
        }
    }
    
    @if (KKK_Zusterna.Models.GlobalNotifications.seznamObvestil != null && KKK_Zusterna.Models.GlobalNotifications.seznamObvestil.Count > 0)
    {
        foreach (string obvestilo in KKK_Zusterna.Models.GlobalNotifications.seznamObvestil)
        {
            <div class="row-fluid">
                <div class="span12">
                    <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>Opravljeno! </strong>@obvestilo 
                    </div>
                </div>
            </div>
        }
    }    

    @if (ViewBag.Data != null)
    {
        <div class="row-fluid">
            <div class="span12">
                <div class="row-fluid">
                    <div class="span12">
                        <h3>Uredi/Izbriši galerijo slik: @ViewBag.Data.Naslov</h3>    
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        <legend>Podatki o galeriji</legend>    
                    </div>
                </div>
                @using (Html.BeginForm("UpdateGalerijaSlik", "Administracija", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div class="row-fluid">
                        <div class="span4">
                            <label>ID galerija:</label>
                            @Html.TextBox("ID_galerijaKategorija", (int)ViewBag.Data.ID_galerijaKategorija, new { placeholder = "ID galerija ...", @readonly = "readonly", @class = "input-block-level" }) 
                        </div>
                        <div class="span4">
                            <label>Spremenil:</label>
                            @Html.TextBox("SpremenilUporabnik", (string)ViewBag.Data.SpremenilUporabnik, new { placeholder = "Uporabnik ...", @readonly = "readonly", @class = "input-block-level" }) 
                        </div>
                        <div class="span4">
                            <label>Datum spremembe:</label>
                            @Html.TextBox("SpremenilDatum", (DateTime)ViewBag.Data.SpremenilDatum, new { placeholder = "Datum zadnje spremembe ...", @readonly = "readonly", @class = "input-block-level" })  
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span12">
                            <label>Naslov:</label>
                            <input class="input-block-level" type="text" name="Naslov" placeholder="Naslov ..." value="@ViewBag.Data.Naslov" required readonly="readonly"> 
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span4">
                            <label>Naslovna slika:</label>
                            <div class="fileupload fileupload-new" data-provides="fileupload">
                                <div class="fileupload-preview thumbnail" style="width: 99%; height: 100%;"><img src="@ViewBag.Data.URLSlika" /></div>
                                <div>
                                    <span class="btn btn-file"><span class="fileupload-new"><i class="icon-upload"></i>  Izberi sliko</span><span class="fileupload-exists"><i class="icon-edit"></i>  Spremeni</span><input type="file" name="NaslovnaSlika" /></span>
                                    <a href="#" class="btn fileupload-exists" data-dismiss="fileupload"><i class="icon-remove"></i>  Odstrani</a>
                                </div>
                            </div>   
                        </div>
                        <div class="span8"></div>
                    </div>
                    <div class="row-fluid">
                        <div class="span12">
                            <legend>Dodaj slike v galerijo:</legend>    
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span12">
                            <div class="fileupload fileupload-new" data-provides="fileupload">
                                <div class="input-append">
                                    <div class="uneditable-input span3"><i class="icon-file fileupload-exists"></i> <span class="fileupload-preview"></span></div><span class="btn btn-file"><span class="fileupload-new"><i class="icon-upload"></i>  Izberi slike</span><span class="fileupload-exists"><i class="icon-edit"></i>  Spremeni</span><input type="file" name="Slike" multiple /></span><a href="#" class="btn fileupload-exists" data-dismiss="fileupload"><i class="icon-remove"></i>  Odstrani</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    if (ViewBag.Galerija != null && ViewBag.Galerija.Count > 0)
                    {
                        int index = 0;
                        int stevec = 0;

                        while (index != ViewBag.Galerija.Count)
                        {
                            <div class="row-fluid">
                                <ul class="thumbnails">
                                    @for (int i = index; i < ViewBag.Galerija.Count; i++)
                                    {
                                        <li class="span4">
                                            <a href="@ViewBag.Galerija[index].URLSlika" rel="lightbox[@ViewBag.Data.Naslov]" title="" class="thumbnail">
                                                <img class="lazy" data-original="@ViewBag.Galerija[index].URLSlika" alt="" width="100%" height="100%">
                                            </a>
                                            <br />
                                            <a class="btn btn-danger" href="@Url.Action("DeleteSelectedImageFromGalerija", "Administracija", new { ID_galerija = ViewBag.Galerija[index].ID_galerija })"><i class="icon-trash icon-white"></i>  Izbriši sliko</a>
                                        </li> 
                                        stevec++;
                                        index++;
                                        if (stevec == 3)
                                        {
                                            break;
                                        }
                                    }           
                                </ul>
                            </div>
                            stevec = 0;
                        }      
                    }
                    <div class="row-fluid">
                        <div class="span12">
                            <legend>Operacije</legend>    
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span12">
                            <div class="control-group">
                                <div class="controls">
                                    <button class="btn btn-primary" type="submit"><i class="icon-edit icon-white"></i>  Uredi</button>  
                                    <a class="btn btn-danger" href="@Url.Action("DeleteGalerija", "Administracija", new { ID_galerijaKategorija = ViewBag.Data.ID_galerijaKategorija })"><i class="icon-trash icon-white"></i>  Izbriši slike</a>
                                    <a class="btn btn-danger" href="@Url.Action("DeleteGalerijaSlik", "Administracija", new { ID_galerijaKategorija = ViewBag.Data.ID_galerijaKategorija })"><i class="icon-trash icon-white"></i>  Izbriši galerijo</a>
                                    <a class="btn" href="@Url.Action("UrediGalerijoSlik", "Administracija")"><i class="icon-remove"></i>  Zapri</a>
                                </div>
                            </div>    
                        </div>
                    </div>
                }
            </div>
        </div>
    }
    else
    {
        <div class="row-fluid">
            <div class="span12">
                <div class="row-fluid">
                    <div class="span12">
                        <h3>Dodaj galerijo slik</h3>    
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        <legend>Podatki o galeriji</legend>    
                    </div>
                </div>
                @using (Html.BeginForm("InsertGalerijoSlik", "Administracija", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div class="row-fluid">
                        <div class="span12">
                            <label>Naslov:</label>
                            <input class="input-block-level" type="text" name="Naslov" placeholder="Naslov ..." required>  
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span4">
                            <label>Naslovna slika:</label>
                            <div class="fileupload fileupload-new" data-provides="fileupload">
                                <div class="fileupload-preview thumbnail" style="width: 99%; height: 100%;"></div>
                                <div>
                                    <span class="btn btn-file"><span class="fileupload-new"><i class="icon-upload"></i>  Izberi sliko</span><span class="fileupload-exists"><i class="icon-edit"></i>  Spremeni</span><input type="file" name="NaslovnaSlika" /></span>
                                    <a href="#" class="btn fileupload-exists" data-dismiss="fileupload"><i class="icon-remove"></i>  Odstrani</a>
                                </div>
                            </div>
                        </div>
                        <div class="span8"></div>
                    </div>
                    <div class="row-fluid">
                        <div class="span12">
                            <legend>Dodaj slike v galerijo:</legend>    
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span12">
                            <div class="fileupload fileupload-new" data-provides="fileupload">
                              <div class="input-append">
                                <div class="uneditable-input span3"><i class="icon-file fileupload-exists"></i> <span class="fileupload-preview"></span></div><span class="btn btn-file"><span class="fileupload-new"><i class="icon-upload"></i>  Izberi slike</span><span class="fileupload-exists"><i class="icon-edit"></i>  Spremeni</span><input type="file" name="Slike" multiple /></span><a href="#" class="btn fileupload-exists" data-dismiss="fileupload"><i class="icon-remove"></i>  Odstrani</a>
                              </div>
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span12">
                            <legend>Operacije</legend>    
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span12">
                            <div class="control-group">
                                <div class="controls">
                                    <button class="btn btn-primary" type="submit"><i class="icon-plus icon-white"></i>  Shrani</button>
                                    <a class="btn" href="@Url.Action("UrediGalerijoSlik", "Administracija")"><i class="icon-remove"></i>  Zapri</a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    }
      
</div>