KKK_Zusterna/KKK_Zusterna/Models/GalerijaSlik/Galerija.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KKK_Zusterna.Models
{
    public class Galerija
    {
        #region Properties

        [Required]
        [Display(Name = "Galerija")]
        public int ID_galerija { get; set; }

        [Required]
        [Display(Name = "Galerija kategorija:")]
        public int ID_galerijaKategorija { get; set; }

        [Required]
        [Display(Name = "URL Slika:")]
        public string URLSlika { get; set; }

        #endregion

        #region LifeCycle

        public Galerija(){}

        #endregion
    }
}

KKK_Zusterna/KKK_Zusterna/Models/GalerijaSlik/GalerijaKategorija.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KKK_Zusterna.Models
{
    public class GalerijaKategorija
    {
        #region Properties

        [Required]
        [Display(Name = "Kategorija:")]
        public int ID_galerijaKategorija { get; set; }

        [Required]
        [Display(Name = "Naslov:")]
        public string Naslov { get; set; }

        [Required]
        [Display(Name = "URL Slika:")]
        public string URLSlika { get; set; }

        [Display(Name = "Spremenil uporabnik:")]
        public string SpremenilUporabnik { get; set; }

        [Display(Name = "URL Slika:")]
        public DateTime SpremenilDatum { get; set; }

        #endregion

        #region LifeCycle

        public GalerijaKategorija(){}

        #endregion
    }
}

KKK_Zusterna/KKK_Zusterna/Models/GalerijaSlik/GalerijaKategorijaGrid.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KKK_Zusterna.Models
{
    public class GalerijaKategorijaGrid
    {
        #region Properties

        public int ID_galerijaKategorija { get; set; }
        public string Naslov { get; set; }
        public string URLSlika { get; set; }
        public string SpremenilUporabnik { get; set; }
        public DateTime SpremenilDatum { get; set; }

        #endregion
    }
}

KKK_Zusterna/KKK_Zusterna/Models/GalerijaSlik/GalerijaKategorijaPPP.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SQLite;
using System.Linq;
using System.Web;
using KKK_Zusterna.Helper;

namespace KKK_Zusterna.Models
{
    public class GalerijaKategorijaPPP
    {
        #region ConnectionString

        private string ConnString = System.Configuration.ConfigurationManager.ConnectionStrings["KKKZusternaDB"].ConnectionString;

        #endregion

        #region Functionality

        public List<GalerijaKategorijaGrid> VrniKategorijeSlik()
        {
            List<GalerijaKategorijaGrid> seznamKategorij = new List<GalerijaKategorijaGrid>();

            string query = @"SELECT GalerijaKategorija.ID_galerijaKategorija, GalerijaKategorija.Naslov, GalerijaKategorija.URLSlika, GalerijaKategorija.SpremenilUporabnik, GalerijaKategorija.SpremenilDatum 
                             FROM GalerijaKategorija
                             ORDER BY ID_galerijaKategorija DESC";

            SQLiteConnection conn = new SQLiteConnection(ConnString);

            conn.Open();

            SQLiteCommand cmd = new SQLiteCommand(conn);
            cmd.CommandText = query;

            SQLiteDataReader reader = cmd.ExecuteReader();

            DataSet ds = new DataSet();
            DataTable dt = new DataTable();

            ds.Tables.Add(dt);
            ds.EnforceConstraints = false;
            dt.Load(reader);

            conn.Dispose();

            //Pretvorimo dt v List<GalerijaKategorijaGrid>
            if (ds != null)
            {
                DataTableToList<GalerijaKategorijaGrid> dtl = new DataTableToList<GalerijaKategorijaGrid>();
                seznamKategorij = dtl.FromDataTableToList(ds.Tables[0]);
            }

            return seznamKategorij;
        }

        public List<GalerijaKategorijaGrid> VrniKategorijeSlikFiltered(string id, string naslov)
        {
            List<GalerijaKategorijaGrid> seznamKategorij = new List<GalerijaKategorijaGrid>();

            string query = "";

            if (id != "" && Uspeh(id))
            {
                query = @"SELECT GalerijaKategorija.ID_galerijaKategorija, GalerijaKategorija.Naslov, GalerijaKategorija.URLSlika, GalerijaKategorija.SpremenilUporabnik, GalerijaKategorija.SpremenilDatum 
                             FROM GalerijaKategorija
                             WHERE ID_galerijaKategorija = '" + id + "' ";
            }
            else
            {
                query = @"SELECT GalerijaKategorija.ID_galerijaKategorija, GalerijaKategorija.Naslov, GalerijaKategorija.URLSlika, GalerijaKategorija.SpremenilUporabnik, GalerijaKategorija.SpremenilDatum 
                             FROM GalerijaKategorija
                             WHERE Naslov LIKE '%" + naslov + "%' ";   
            }

            SQLiteConnection conn = new SQLiteConnection(ConnString);

            conn.Open();

            SQLiteCommand cmd = new SQLiteCommand(conn);
            cmd.CommandText = query;

            SQLiteDataReader reader = cmd.ExecuteReader();

            DataSet ds = new DataSet();
            DataTable dt = new DataTable();

            ds.Tables.Add(dt);
            ds.EnforceConstraints = false;
            dt.Load(reader);

            conn.Dispose();

            //Pretvorimo dt v List<GalerijaKategorijaGrid>
            if (ds != null)
            {
                DataTableToList<GalerijaKategorijaGrid> dtl = new DataTableToList<GalerijaKategorijaGrid>();
                seznamKategorij = dtl.FromDataTableToList(ds.Tables[0]);
            }

            return seznamKategorij;
        }

        public GalerijaKategorija VrniKategorijoSlik(int id)
        {
            GalerijaKategorija galerijaKategorija = null;

            string query = @"SELECT GalerijaKategorija.ID_galerijaKategorija, GalerijaKategorija.Naslov, GalerijaKategorija.URLSlika, GalerijaKategorija.SpremenilUporabnik, GalerijaKategorija.SpremenilDatum 
                             FROM GalerijaKategorija
                             WHERE ID_galerijaKategorija = '" + id + "' ";

            SQLiteConnection conn = new SQLiteConnection(ConnString);

            conn.Open();

            SQLiteCommand cmd = new SQLiteCommand(conn);
            cmd.CommandText = query;

            SQLiteDataReader reader = cmd.ExecuteReader();

            DataSet ds = new DataSet();
            DataTable dt = new DataTable();

            ds.Tables.Add(dt);
            ds.EnforceConstraints = false;
            dt.Load(reader);

            conn.Dispose();

            if (dt != null && dt.Rows.Count > 0)
            {
                galerijaKategorija = new GalerijaKategorija();

                galerijaKategorija.ID_galerijaKategorija = (int)dt.Rows[0]["ID_galerijaKategorija"];
                galerijaKategorija.Naslov = (string)dt.Rows[0]["Naslov"];
                galerijaKategorija.URLSlika = dt.Rows[0]["URLSlika"] != null ? (string)dt.Rows[0]["URLSlika"] : "";
                galerijaKategorija.SpremenilUporabnik = dt.Rows[0]["SpremenilUporabnik"] != null ? (string)dt.Rows[0]["SpremenilUporabnik"] : "";
                galerijaKategorija.SpremenilDatum = dt.Rows[0]["SpremenilDatum"] != null ? (DateTime)dt.Rows[0]["SpremenilDatum"] : System.DateTime.Now;
            }

            return galerijaKategorija;
        }

        public int GetNextIDGalerijaKategorija()
        {
            int nextIdGalerijaKategorija = 0;

            string query = @"SELECT MAX(ID_galerijaKategorija) AS Stevilo FROM GalerijaKategorija";

            SQLiteConnection conn = new SQLiteConnection(ConnString);

            conn.Open();

            SQLiteCommand cmd = new SQLiteCommand(conn);
            cmd.CommandText = query;

            try
            {
                nextIdGalerijaKategorija = (Convert.ToInt32(cmd.ExecuteScalar())) + 1;
            }
            catch (Exception)
            {
                nextIdGalerijaKategorija = 1;
            }

            conn.Dispose();

            return nextIdGalerijaKategorija;
        }

        public void InsertGalerijaKategorija(GalerijaKategorija galerijaKategorija)
        {
            string query = @"INSERT INTO GalerijaKategorija 
                             VALUES ('" + galerijaKategorija.ID_galerijaKategorija + "', '" + galerijaKategorija.Naslov + "', '" + galerijaKategorija.URLSlika + "', '" + galerijaKategorija.SpremenilUporabnik + "', DATETIME('now') )";

            SQLiteConnection conn = new SQLiteConnection(ConnString);

            conn.Open();

            SQLiteCommand cmd = new SQLiteCommand(conn);
            cmd.CommandText = query;

            cmd.ExecuteNonQuery();

            conn.Dispose();
        }

        public void UpdateGalerijaKategorija(GalerijaKategorija galerijaKategorija)
        {
            string query = @"UPDATE GalerijaKategorija 
                             SET Naslov = '" + galerijaKategorija.Naslov + "', URLSlika ='" + galerijaKategorija.URLSlika + "', SpremenilUporabnik = '" + galerijaKategorija.SpremenilUporabnik + "', SpremenilDatum = DATETIME('now') " +
                           " WHERE ID_galerijaKategorija = '" + galerijaKategorija.ID_galerijaKategorija + "' ";

            SQLiteConnection conn = new SQLiteConnection(ConnString);

            conn.Open();

            SQLiteCommand cmd = new SQLiteCommand(conn);
            cmd.CommandText = query;

            cmd.ExecuteNonQuery();

            conn.Dispose();
        }

        public void DeleteGalerijaKategorija(int id_galerijaKategorija)
        {
            string query = "DELETE FROM GalerijaKategorija WHERE ID_galerijaKategorija = '" + id_galerijaKategorija + "' ";

            SQLiteConnection conn = new SQLiteConnection(ConnString);

            conn.Open();

            SQLiteCommand cmd = new SQLiteCommand(conn);
            cmd.CommandText = query;

            cmd.ExecuteNonQuery();

            conn.Dispose();
        }

        public bool Uspeh(string naziv)
        {
            try
            {
                int.Parse(naziv);

                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }

        #endregion
    }
}

KKK_Zusterna/KKK_Zusterna/Controllers/SplosnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using KKK_Zusterna.Models;
using KKK_Zusterna.Helper;
using PagedList;
using log4net;

namespace KKK_Zusterna.Controllers
{
    public class SplosnoController : Controller
    {
        #region Properties

        ILog logger = LogManager.GetLogger(typeof(SplosnoController));

        private GalerijaKategorijaPPP UpraviteljGalerijaKategorija = new GalerijaKategorijaPPP();

        private GalerijaPPP UpraviteljGalerija = new GalerijaPPP();

        #endregion

        #region Splosno

        #region Galerija slik

        #region Galerija slik

        public ActionResult GalerijaSlik(int? page)
        {
            int pageSize = 4;
            int pageNumber = (page ?? 1);

            List<GalerijaKategorijaGrid> galerije = null;

            try
            {
                //Zbrisemo obvestila && napake
                GlobalNotifications.ZbrisiObvestilo();
                GlobalErrors.ZbrisiNapake();
                GlobalWarnings.ZbrisiOpozorilo();

                galerije = UpraviteljGalerijaKategorija.VrniKategorijeSlik();

                //Obvestilo o uspehu akcije if TrenutniUporabnik != null
                if (System.Web.HttpContext.Current.User.Identity.IsAuthenticated)
                {
                    GlobalNotifications.DodajObvestilo(GlobalNotifications.UspehOperacije);
                }
            }
            catch (Exception ex)
            {
                GlobalErrors.ZbrisiNapake();
                GlobalErrors.DodajNapako(ex.ToString());
                MailHelper.SendMailForErrors("GalerijaSlik", ex.ToString());
                logger.Error("ERROR in method " + MethodInfo.GetCurrentMethod() + ": " + ex);
            }

            return View(galerije.ToPagedList(pageNumber, pageSize));
        }

        #endregion

        #region PrikaziGalerijo

        public ActionResult PrikaziGalerijo(int ID_galerijaKategorija, int? page)
        {
            int pageSize = 9;
            int pageNumber = (page ?? 1);

            GalerijaKategorija galerijaKategorija = null;
            List<Galerija> galerija = null;

            try
            {
                //Zbrisemo obvestila && napake
                GlobalNotifications.ZbrisiObvestilo();
                GlobalErrors.ZbrisiNapake();
                GlobalWarnings.ZbrisiOpozorilo();

                //Get galerija
                galerijaKategorija = UpraviteljGalerijaKategorija.VrniKategorijoSlik(ID_galerijaKategorija);
                galerija = UpraviteljGalerija.VrniGalerijoZaGalerijaKategorija(ID_galerijaKategorija);

                //Obvestilo o uspehu akcije if TrenutniUporabnik != null
                if (System.Web.HttpContext.Current.User.Identity.IsAuthenticated)
                {
                    GlobalNotifications.DodajObvestilo(GlobalNotifications.UspehOperacije);
                }
            }
            catch (Exception ex)
            {
                GlobalErrors.ZbrisiNapake();
                GlobalErrors.DodajNapako(ex.ToString());
                MailHelper.SendMailForErrors("PrikaziGalerijo", ex.ToString());
                logger.Error("ERROR in method " + MethodInfo.GetCurrentMethod() + ": " + ex);
            }

            return View("Galerija", Tuple.Create(galerijaKategorija, galerija.ToPagedList(pageNumber, pageSize)));
        }

        #endregion

        #endregion

        #endregion
    }
}

KKK_Zusterna/KKK_Zusterna/Views/Splosno/Galerija.cshtml
@model Tuple<KKK_Zusterna.Models.GalerijaKategorija, PagedList.IPagedList<KKK_Zusterna.Models.Galerija>>
@using PagedList.Mvc;    

@{
    ViewBag.Title = "Kajak kanu klub Žusterna";
}
<div class="span12">
    @if (KKK_Zusterna.Models.GlobalErrors.seznamNapak != null && KKK_Zusterna.Models.GlobalErrors.seznamNapak.Count > 0)
    {
        foreach (string napaka in KKK_Zusterna.Models.GlobalErrors.seznamNapak)
        {
        <div class="row-fluid">
            <div class="span12">
                <div class="alert alert-error">
                    <button type="button" class="close" data-dismiss="alert">
                        &times;</button>
                    <strong>Napaka!</strong><br />
                    @napaka
                </div>
            </div>
        </div> 
        }
    }
    
    @if (KKK_Zusterna.Models.GlobalWarnings.seznamOpozoril != null && KKK_Zusterna.Models.GlobalWarnings.seznamOpozoril.Count > 0)
    {
        foreach (string opozorilo in KKK_Zusterna.Models.GlobalWarnings.seznamOpozoril)
        {
            <div class="row-fluid">
                <div class="span12">
                    <div class="alert alert-info">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>Opozorilo!</strong><br /> @opozorilo
                    </div> 
                </div>
            </div> 
        }
    }

    @if (KKK_Zusterna.Models.GlobalNotifications.seznamObvestil != null && KKK_Zusterna.Models.GlobalNotifications.seznamObvestil.Count > 0)
    {
        foreach (string obvestilo in KKK_Zusterna.Models.GlobalNotifications.seznamObvestil)
        {
        <div class="row-fluid">
            <div class="span12">
                <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert">
                        &times;</button>
                    <strong>Opravljeno! </strong>@obvestilo
                </div>
            </div>
        </div>
        }
    }
    
    @if (Model.Item2 != null && Model.Item2.Count > 0)
    {
        <ul class="breadcrumb alert alert-info">
            <li><a href="@Url.Action("GalerijaSlik", "Splosno")">Galerija slik</a> <span class="divider">/</span></li>
            <li class="active">@Model.Item1.Naslov</li>
        </ul>
        
        int index = 0;
        int stevec = 0;

        while (index != Model.Item2.Count)
        {
            <div class="row-fluid">
                <ul class="thumbnails">
                    @for (int i = index; i < Model.Item2.Count; i++)
                    {
                        <li class="span4">
                            <a href="@Model.Item2[index].URLSlika" rel="lightbox[@Model.Item1.Naslov]" title="" class="thumbnail">
                                <img class="lazy" data-original="@Model.Item2[index].URLSlika" alt="" width="100%" height="100%">
                            </a>
                        </li> 
                        stevec++;
                        index++;
                        if (stevec == 3)
                        {
                            break;
                        }
                    }           
                </ul>
            </div>
            stevec = 0;
        }
        
        @Html.PagedListPager(Model.Item2, page => Url.Action("PrikaziGalerijo", "Splosno", new { ID_galerijaKategorija = Model.Item1.ID_galerijaKategorija, page }))
        
        <div class="row-fluid">
            <div class="span12">
                <legend>Informacije o galeriji:</legend>    
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <span class="muted">Objavil: @Model.Item1.SpremenilUporabnik</span>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <span class="muted">Datum objave: @Model.Item1.SpremenilDatum</span>
            </div>
        </div>
    }
    else
    {
        <div class="row-fluid">
            <div class="span12">
                <div class="alert alert-info">
                    <button type="button" class="close" data-dismiss="alert">
                        &times;</button>
                    <strong>Opozorilo!</strong> Ni dodanih slik.
                </div>
            </div>
        </div>
        
        <ul class="breadcrumb alert alert-info">
          <li><a href="@Url.Action("GalerijaSlik", "Splosno")">Galerija slik</a> <span class="divider">/</span></li>
          <li class="active">@Model.Item1.Naslov</li>
        </ul>
    }
</div>

KKK_Zusterna/KKK_Zusterna/Views/Splosno/GalerijaSlik.cshtml
@model PagedList.IPagedList<KKK_Zusterna.Models.GalerijaKategorijaGrid>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Kajak kanu klub Žusterna";
}
<div class="span12">
    @if (KKK_Zusterna.Models.GlobalErrors.seznamNapak != null && KKK_Zusterna.Models.GlobalErrors.seznamNapak.Count > 0)
    {
        foreach (string napaka in KKK_Zusterna.Models.GlobalErrors.seznamNapak)
        {
        <div class="row-fluid">
            <div class="span12">
                <div class="alert alert-error">
                    <button type="button" class="close" data-dismiss="alert">
                        &times;</button>
                    <strong>Napaka!</strong><br />
                    @napaka
                </div>
            </div>
        </div> 
        }
    }
    
    @if (KKK_Zusterna.Models.GlobalWarnings.seznamOpozoril != null && KKK_Zusterna.Models.GlobalWarnings.seznamOpozoril.Count > 0)
    {
        foreach (string opozorilo in KKK_Zusterna.Models.GlobalWarnings.seznamOpozoril)
        {
            <div class="row-fluid">
                <div class="span12">
                    <div class="alert alert-info">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>Opozorilo!</strong><br /> @opozorilo
                    </div> 
                </div>
            </div> 
        }
    }

    @if (KKK_Zusterna.Models.GlobalNotifications.seznamObvestil != null && KKK_Zusterna.Models.GlobalNotifications.seznamObvestil.Count > 0)
    {
        foreach (string obvestilo in KKK_Zusterna.Models.GlobalNotifications.seznamObvestil)
        {
        <div class="row-fluid">
            <div class="span12">
                <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert">
                        &times;</button>
                    <strong>Opravljeno! </strong>@obvestilo
                </div>
            </div>
        </div>
        }
    }
    @if (Model != null && Model.Count > 0)
    {
        <ul class="breadcrumb alert alert-info">
          <li class="active">Galerija slik</li>
        </ul>

        foreach (var galerijaKategorija in Model)
        {
            <div class="row-fluid">
                <div class="span12">
                    <div class="span3">
                        <ul class="thumbnails">
                            <li class="span12">
                                <a href="@Url.Action("PrikaziGalerijo", "Splosno", new { ID_galerijaKategorija = galerijaKategorija.ID_galerijaKategorija })" class="thumbnail">
                                    <img class="lazy" data-original="@galerijaKategorija.URLSlika" alt="" width="100%" height="100%">
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="span9">
                        <div class="span9">
                            <div class="row-fluid">
                                <div class="span12">
                                    <a href="@Url.Action("PrikaziGalerijo", "Splosno", new { ID_galerijaKategorija = galerijaKategorija.ID_galerijaKategorija })"><h4>@galerijaKategorija.Naslov</h4></a>
                                </div>
                            </div>
                            <div class="row-fluid">
                                <div class="span12">
                                    <span class="muted">Objavil: @galerijaKategorija.SpremenilUporabnik</span>
                                </div>
                            </div>
                            <div class="row-fluid">
                                <div class="span12">
                                    <span class="muted">Datum objave: @galerijaKategorija.SpremenilDatum</span>
                                </div>
                            </div>
                        </div>
                    </div>    
                </div>
            </div>
        }
        
        @Html.PagedListPager(Model, page => Url.Action("GalerijaSlik", "Splosno", new { page }))
    }
    else
    {
        <div class="row-fluid">
            <div class="span12">
                <div class="alert alert-info">
                    <button type="button" class="close" data-dismiss="alert">
                        &times;</button>
                    <strong>Opozorilo!</strong> Ni dodanih galerij.
                </div>
            </div>
        </div>
        
        <ul class="breadcrumb alert alert-info">
          <li class="active">Galerija slik</li>
        </ul>
    }
</div>